const Map<String, List<String>> elderSafeInternetTips = {
  "en": [
    "Do not click unknown links sent by SMS or WhatsApp.",
    "Never share OTP, bank details, or passwords.",
    "Government or banks never ask for money on phone calls.",
    "Check sender name before trusting messages.",
    "Ask family members if you are unsure.",
    "Do not install apps suggested by unknown callers.",
    "Do not share UPI QR codes or scan unknown QR codes.",
    "Scammers may pretend to be relatives or officials.",
    "Do not respond to messages that create urgency or fear.",
    "Avoid sharing personal photos or documents online.",
    "Do not trust prize or lottery winning messages.",
    "Always verify messages claiming account suspension.",
    "Do not answer video calls from unknown numbers.",
    "Keep phone screen lock enabled at all times.",
    "Report suspicious messages to family immediately.",
  ],
  "hi": [
    "SMS या WhatsApp पर आए अनजान लिंक पर क्लिक न करें।",
    "OTP, बैंक जानकारी या पासवर्ड कभी साझा न करें।",
    "सरकार या बैंक फोन पर पैसे नहीं मांगते।",
    "भरोसा करने से पहले भेजने वाले का नाम जांचें।",
    "अगर संदेह हो तो परिवार से पूछें।",
    "अनजान कॉलर द्वारा बताए गए ऐप इंस्टॉल न करें।",
    "UPI QR कोड साझा न करें या अनजान QR स्कैन न करें।",
    "ठग रिश्तेदार या अधिकारी बनकर बात कर सकते हैं।",
    "डर या जल्दी पैदा करने वाले संदेशों पर भरोसा न करें।",
    "व्यक्तिगत फोटो या दस्तावेज ऑनलाइन साझा न करें।",
    "इनाम या लॉटरी जीतने वाले संदेशों पर भरोसा न करें।",
    "खाता बंद होने का दावा करने वाले संदेश सत्यापित करें।",
    "अनजान नंबर से वीडियो कॉल न उठाएं।",
    "हमेशा मोबाइल में स्क्रीन लॉक चालू रखें।",
    "संदिग्ध संदेश तुरंत परिवार को दिखाएं।",
  ],
  "mr": [
    "SMS किंवा WhatsApp वर आलेल्या अनोळखी लिंकवर क्लिक करू नका.",
    "OTP, बँक माहिती किंवा पासवर्ड कधीही सांगू नका.",
    "सरकार किंवा बँक फोनवर पैसे मागत नाही.",
    "विश्वास ठेवण्यापूर्वी पाठवणाऱ्याचे नाव तपासा.",
    "संशय असल्यास कुटुंबीयांना विचारा.",
    "अनोळखी कॉल करणाऱ्यांनी सांगितलेले अ‍ॅप्स इंस्टॉल करू नका.",
    "UPI QR कोड शेअर करू नका किंवा अनोळखी QR स्कॅन करू नका.",
    "फसवणूक करणारे नातेवाईक किंवा अधिकारी असल्याचे नाटक करू शकतात.",
    "भीती किंवा घाई निर्माण करणाऱ्या संदेशांवर विश्वास ठेवू नका.",
    "वैयक्तिक फोटो किंवा कागदपत्रे ऑनलाइन पाठवू नका.",
    "बक्षीस किंवा लॉटरी जिंकल्याचे संदेश खरे नसतात.",
    "खाते बंद होणार असल्याचे सांगणारे संदेश तपासा.",
    "अनोळखी नंबरवरून आलेल्या व्हिडिओ कॉल्स उचलू नका.",
    "नेहमी मोबाईलवर स्क्रीन लॉक चालू ठेवा.",
    "संशयास्पद संदेश त्वरित कुटुंबाला दाखवा.",
  ],
};
