const Map<String, List<String>> elderLessons = {
  "en": [
    "Never share OTP with anyone.",
    "Banks never ask for your password or PIN.",
    "Do not click unknown links sent by SMS or WhatsApp.",
    "If you win a prize, verify it with your family first.",
    "Government officers never ask for money on phone calls.",
    "Do not install apps suggested by unknown callers.",
    "Scammers may pretend to be your relatives.",
    "Never share UPI QR codes or bank details.",
    "Disconnect calls that threaten arrest or fine.",
    "Always ask a trusted person before acting.",
    "Do not respond to urgent money requests.",
    "Never share Aadhaar or PAN details on call.",
    "Do not believe callers claiming lottery wins.",
    "Banks do not ask you to update details by phone.",
    "Avoid sharing personal details on social media.",
    "Unknown callers may use fear to cheat you.",
    "Do not trust caller ID names blindly.",
    "Never allow remote access to your phone.",
    "Do not call back unknown missed calls.",
    "Verify messages before forwarding.",
    "Scammers may offer fake job opportunities.",
    "Avoid talking to strangers about finances.",
    "Never press numbers when asked by unknown callers.",
    "Do not share card CVV number.",
    "Avoid public Wi-Fi for banking apps.",
    "Keep your phone updated.",
    "Do not believe urgent medical emergency calls.",
    "Fraudsters may speak politely to gain trust.",
    "Always double-check before sending money.",
    "When in doubt, hang up the call."
  ],
  "hi": [
    "किसी को भी ओटीपी न दें।",
    "बैंक कभी पासवर्ड या पिन नहीं पूछते।",
    "अज्ञात लिंक पर क्लिक न करें।",
    "इनाम जीतने की बात पहले परिवार से जांचें।",
    "सरकारी अधिकारी फोन पर पैसे नहीं मांगते।",
    "अज्ञात कॉलर द्वारा बताए गए ऐप इंस्टॉल न करें।",
    "ठग रिश्तेदार बनकर बात कर सकते हैं।",
    "यूपीआई क्यूआर कोड या बैंक जानकारी साझा न करें।",
    "गिरफ्तारी या जुर्माने की धमकी वाले कॉल काट दें।",
    "किसी भरोसेमंद व्यक्ति से सलाह लें।",
    "तुरंत पैसे मांगने वाले कॉल से सावधान रहें।",
    "आधार या पैन की जानकारी फोन पर न दें।",
    "लॉटरी जीतने वाले कॉल पर भरोसा न करें।",
    "बैंक फोन पर जानकारी अपडेट नहीं कराते।",
    "सोशल मीडिया पर निजी जानकारी साझा न करें।",
    "डर दिखाकर ठगी की जा सकती है।",
    "कॉलर आईडी पर आंख बंद करके भरोसा न करें।",
    "फोन का रिमोट एक्सेस किसी को न दें।",
    "अनजान मिस्ड कॉल पर वापस कॉल न करें।",
    "मैसेज आगे भेजने से पहले जांचें।",
    "नकली नौकरी के ऑफर से सावधान रहें।",
    "पैसों की बात अजनबियों से न करें।",
    "अनजान कॉल पर नंबर न दबाएं।",
    "कार्ड का सीवीवी नंबर न बताएं।",
    "पब्लिक वाई-फाई पर बैंकिंग ऐप न चलाएं।",
    "फोन को अपडेट रखें।",
    "फर्जी मेडिकल इमरजेंसी कॉल से बचें।",
    "ठग मीठी भाषा का उपयोग कर सकते हैं।",
    "पैसे भेजने से पहले दो बार जांचें।",
    "संदेह हो तो कॉल काट दें।"
  ],
  "mr": [
    "कोणालाही ओटीपी सांगू नका.",
    "बँक कधीही पासवर्ड किंवा पिन विचारत नाही.",
    "अनोळखी लिंकवर क्लिक करू नका.",
    "बक्षीस जिंकल्याचा दावा आधी कुटुंबाशी तपासा.",
    "सरकारी अधिकारी फोनवर पैसे मागत नाहीत.",
    "अनोळखी व्यक्तीने सांगितलेले ॲप्स इंस्टॉल करू नका.",
    "फसवणूक करणारे नातेवाईक असल्याचे भासवू शकतात.",
    "यूपीआय क्यूआर कोड किंवा बँक तपशील शेअर करू नका.",
    "अटक किंवा दंडाची धमकी देणारे कॉल कट करा.",
    "विश्वासू व्यक्तीचा सल्ला घ्या.",
    "तात्काळ पैसे मागणाऱ्या कॉलपासून सावध रहा.",
    "आधार किंवा पॅन नंबर फोनवर देऊ नका.",
    "लॉटरी जिंकल्याच्या कॉलवर विश्वास ठेवू नका.",
    "बँक फोनवर माहिती अपडेट करत नाही.",
    "सोशल मीडियावर वैयक्तिक माहिती टाकू नका.",
    "भीती दाखवून फसवणूक केली जाऊ शकते.",
    "कॉलर आयडीवर पूर्ण विश्वास ठेवू नका.",
    "फोनचा रिमोट अॅक्सेस कोणालाही देऊ नका.",
    "अनोळखी मिस्ड कॉलला परत कॉल करू नका.",
    "मेसेज फॉरवर्ड करण्यापूर्वी तपासा.",
    "नकली नोकरीच्या ऑफरपासून सावध रहा.",
    "पैशांबाबत अजनब्यांशी बोलू नका.",
    "अनोळखी कॉलवर नंबर दाबू नका.",
    "कार्डचा सीव्हीव्ही नंबर सांगू नका.",
    "सार्वजनिक वाय-फायवर बँकिंग वापरू नका.",
    "फोन नेहमी अपडेट ठेवा.",
    "खोट्या वैद्यकीय आपत्कालीन कॉलपासून दूर रहा.",
    "फसवणूक करणारे गोड बोलू शकतात.",
    "पैसे पाठवण्याआधी दोनदा खात्री करा.",
    "शंका असल्यास कॉल कट करा."
  ],
};
